# -*- coding: utf-8 -*-
"""COP1000_Module02_PersonalInformation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfzhPJoeMFsEVfd1k532N8R9npwrkz7V
"""

first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
age = input("Enter your age: ")
city = input("Enter your city ")
career_interest = (input("Enter your career interest: "))

# Age conversion
age = int(age)
new_age = age + 1

# Spacer
print("")

print(f"---Personal Information---")

# Spacer
print("")

print(f"Name: {first_name} {last_name}")
print(f"Age: {age}")
print(f"Age Next Year {new_age}")
print(f"City: {city}")
print(f"Career interest: {career_interest}")