# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTHXv2WkILpS2Ehd9LlAo74raewRJKx-
"""

print("Hello, my name is Hunter Prince. I flew drones for the military for reconnaissance missions.")

# My interest for now is self improving for personal equipment at home
print("I believe python will be easy. I just need to make sure I understand the proper commands and uses for each problem. ")

print("I want to go into some sort of security. At the same time I also want to be on the server maintenance side.")

print("I am excited to get educated in this practice. Can't wait to see my progression.")

