# -*- coding: utf-8 -*-
"""COP1000_Module04_GuessTheNumber.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JWGITSjCKkaFJkg01q7u1tV6BL3mM-3
"""

import random

secret_number = random.randint(1, 20)
attempts = 0

print("Welcome to Guess the Number!")
print("I am thinkning of a number form 1 to 20.")

while True:
    guess = int(input("Enter your guess: "))
    attempts += 1

    if guess == secret_number:
        print(f"Correct!")
        print(f"You guessed the number in {attempts} attempts.")
        break
    elif guess < secret_number:
        print("Too low! Try again.")
    else:
        print("Too high! Try again.")