# -*- coding: utf-8 -*-
"""COP1000_Module03_DecisionTool.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BeAwVlUImgWUlpaier7XgMCiu6VeWovY
"""

temperature = input("What is the current temperature? ")
temperature1 = int(temperature)
is_raining = input("Is it raining? Yes or No: ")

if is_raining == "yes":
  print("It is raining. We recommend an indoor activity like bowling or a movie!" )
elif is_raining == "no" and temperature1 < 60:
  print("The weather is chilly. We recommend a nice cup up coffee and a small coat. ")
elif is_raining == "no" and temperature1 >= 60 and temperature1 <= 84:
  print("The weather is in it's best condition. We recommend going for a walk, or even mountain climbing. ")
else:
  print("It is very hot! We recoomend and activity like swimming! ")