# -*- coding: utf-8 -*-
"""COP1000_Module05_TipCalculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lPmzu1F_dOuAeDS_SUvaH7HoqKaTYQm
"""

def calculate_tip(bill, tip_percentage):
    tip_rate = tip_percentage / 100
    return bill * tip_rate

def calculate_total_bill(bill, tip):
    return bill + tip

print("TIP CALCULATOR")
print() #

bill_amount = float(input("Enter the total bill amount: "))
tip_percentage = float(input("Enter the tip percentage: "))

calculated_tip = calculate_tip(bill_amount, tip_percentage)
total_bill = calculate_total_bill(bill_amount, calculated_tip)

print(f"Bill: ${bill_amount:}")
print(f"Tip: ${calculated_tip:}")
print(f"Total Bill: ${total_bill:}")