# -*- coding: utf-8 -*-
"""COP1000_Module07_ContactBook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwTe_MJn_bmnQTaeH60PopRk9j1IS79L
"""

###################Contact Book Application####################
contacts = {
    "Sammy": "165-8764",
    "Dawson": "918-8764",
    "Lawrence": "615-3465"
}

print("Contact Book")

print("\nAvailable Contacts:")
for name in contacts:
    print(name)

name_search = input("Enter a contact name:")

if name_search in contacts:
    print(f"{name_search}'s phone number is {contacts[name_search]}.")
else:
    print("Contact not found")