# -*- coding: utf-8 -*-
"""COP1000_Module06_TodoList.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grzgz-P9AdxYs7b1C5XVW8G4FXfnQD-g
"""

todo_list = []

print("To-Do List Manager\n")

for i in range (1, 4):
    task = input(f"Enter task {i}: ")
    todo_list.append(task)

print("\n#----#----# To-Do List #----#----#\n")

for index, task in enumerate(todo_list, start=1):
    print(f"{index}. {task}")
print(f"\nTotal Tasks {len(todo_list)}")